version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory

  post_build:
    commands:
      # Remove existing node_modules to clear dev dependencies

      # Install runtime dependencies
    - npm install --production
    - npm run timestampFix

      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
